import React, { useState } from "react"

const TestCardPage = () => {
  

  const posts = [
    {
      id: 1,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 2,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 3,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 4,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 5,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 6,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 7,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 8,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 9,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 10,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 11,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 12,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 13,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 14,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 15,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 16,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 17,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 18,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 19,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 20,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 21,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 22,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 23,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 24,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 25,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 26,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 27,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 28,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 29,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 30,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 31,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 32,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 33,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 34,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 35,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 36,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 37,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 38,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 39,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 40,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 41,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 42,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 43,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 44,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 45,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 46,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 47,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 48,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 49,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 50,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 51,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 52,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 53,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 54,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 55,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 56,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 57,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 58,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 59,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
      id: 60,
      image: "https://via.placeholder.com/150",
      title: "게시물 제목 1",
      author: "작성자 1",
      date: "2023-09-20",
      rating: 4.5,
      views: 1200,
      country: "대한민국",
      city: "서울",
      tags: ["여행", "맛집", "역사"],
    },
    {
        id: 61,
        image: "https://via.placeholder.com/150",
        title: "게시물 제목 1",
        author: "작성자 1",
        date: "2023-09-20",
        rating: 4.5,
        views: 1200,
        country: "대한민국",
        city: "서울",
        tags: ["여행", "맛집", "역사"],
      },
      {
        id: 62,
        image: "https://via.placeholder.com/150",
        title: "게시물 제목 1",
        author: "작성자 1",
        date: "2023-09-20",
        rating: 4.5,
        views: 1200,
        country: "대한민국",
        city: "서울",
        tags: ["여행", "맛집", "역사"],
      },
      {
        id: 63,
        image: "https://via.placeholder.com/150",
        title: "게시물 제목 1",
        author: "작성자 1",
        date: "2023-09-20",
        rating: 4.5,
        views: 1200,
        country: "대한민국",
        city: "서울",
        tags: ["여행", "맛집", "역사"],
      },
      {
        id: 64,
        image: "https://via.placeholder.com/150",
        title: "게시물 제목 1",
        author: "작성자 1",
        date: "2023-09-20",
        rating: 4.5,
        views: 1200,
        country: "대한민국",
        city: "서울",
        tags: ["여행", "맛집", "역사"],
      },
      {
        id: 65,
        image: "https://via.placeholder.com/150",
        title: "게시물 제목 1",
        author: "작성자 1",
        date: "2023-09-20",
        rating: 4.5,
        views: 1200,
        country: "대한민국",
        city: "서울",
        tags: ["여행", "맛집", "역사"],
      },
      {
        id: 66,
        image: "https://via.placeholder.com/150",
        title: "게시물 제목 1",
        author: "작성자 1",
        date: "2023-09-20",
        rating: 4.5,
        views: 1200,
        country: "대한민국",
        city: "서울",
        tags: ["여행", "맛집", "역사"],
      },
      {
        id: 67,
        image: "https://via.placeholder.com/150",
        title: "게시물 제목 1",
        author: "작성자 1",
        date: "2023-09-20",
        rating: 4.5,
        views: 1200,
        country: "대한민국",
        city: "서울",
        tags: ["여행", "맛집", "역사"],
      },
      {
        id: 68,
        image: "https://via.placeholder.com/150",
        title: "게시물 제목 1",
        author: "작성자 1",
        date: "2023-09-20",
        rating: 4.5,
        views: 1200,
        country: "대한민국",
        city: "서울",
        tags: ["여행", "맛집", "역사"],
      },
      {
        id: 69,
        image: "https://via.placeholder.com/150",
        title: "게시물 제목 1",
        author: "작성자 1",
        date: "2023-09-20",
        rating: 4.5,
        views: 1200,
        country: "대한민국",
        city: "서울",
        tags: ["여행", "맛집", "역사"],
      },
      {
        id: 70,
        image: "https://via.placeholder.com/150",
        title: "게시물 제목 1",
        author: "작성자 1",
        date: "2023-09-20",
        rating: 4.5,
        views: 1200,
        country: "대한민국",
        city: "서울",
        tags: ["여행", "맛집", "역사"],
      },
    // 총 50개의 게시물 샘플 데이터 생성 (페이지 5개를 처리할 수 있도록)
    // ... (생략된 데이터)
  ]

  const [currentPage, setCurrentPage] = useState(1) // 현재 페이지
  const cardsPerPage = 12 // 한 페이지에 보여줄 카드 수
  const totalPages = Math.ceil(posts.length / cardsPerPage) // 총 페이지 수

  // 페이지당 보여줄 게시물 계산
  const indexOfLastPost = currentPage * cardsPerPage
  const indexOfFirstPost = indexOfLastPost - cardsPerPage
  const currentPosts = posts.slice(indexOfFirstPost, indexOfLastPost)

  // 페이지 번호 계산 (한 번에 5개씩 보여줌)
  const pageNumbers = []
  const maxPageNumbersToShow = 5
  const pageStartIndex = Math.floor((currentPage - 1) / maxPageNumbersToShow) * maxPageNumbersToShow + 1
  const pageEndIndex = Math.min(pageStartIndex + maxPageNumbersToShow - 1, totalPages)

  for (let i = pageStartIndex; i <= pageEndIndex; i++) {
    pageNumbers.push(i)
  }

  // 페이지 변경 핸들러
  const paginate = (pageNumber) => setCurrentPage(pageNumber)

  return (
    <div className="min-h-screen bg-gray-100 py-10">
      <div className="container mx-auto">
        <h1 className="text-3xl font-bold text-center mb-8">게시판</h1>

        {/* 카드 리스트 */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          {currentPosts.map((post) => (
            <div key={post.id} className="bg-white rounded-lg shadow-md overflow-hidden">
              <img src={post.image} alt={post.title} className="w-full h-48 object-cover" />
              <div className="p-4">
                <h2 className="text-lg font-bold">{post.title}</h2>
                <p className="text-sm text-gray-600">작성자: {post.author}</p>
                <p className="text-sm text-gray-600">작성일: {post.date}</p>
                <p className="text-sm text-right text-green-800 font-semibold">
                  {post.country} - {post.city}
                </p>
                <div className="flex justify-between items-center mt-2">
                  <span className="text-yellow-500">⭐ {post.rating.toFixed(1)}</span>
                  <span className="text-sm text-gray-500">조회수: {post.views}</span>
                </div>
                <div className="mt-3">
                  <p className="text-sm font-semibold"></p>
                  <div className="flex flex-wrap gap-1">
                    {post.tags.map((tag, index) => (
                      <span key={index} className="bg-blue-100 text-blue-800 text-xs font-semibold px-2 py-1 rounded">
                        #{tag}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* 페이징 버튼 */}
        <div className="flex justify-center space-x-2">
          <button
            onClick={() => paginate(currentPage - 1)}
            disabled={currentPage === 1}
            className={`px-4 py-2 rounded ${
              currentPage === 1 ? "bg-gray-300 text-gray-500 cursor-not-allowed" : "bg-gray-300 text-gray-700"
            }`}>
            &lt;
          </button>
          {pageNumbers.map((number) => (
            <button
              key={number}
              onClick={() => paginate(number)}
              className={`px-4 py-2 rounded ${
                currentPage === number ? "bg-blue-500 text-white" : "bg-gray-300 text-gray-700"
              }`}>
              {number}
            </button>
          ))}
          <button
            onClick={() => paginate(currentPage + 1)}
            disabled={currentPage === totalPages}
            className={`px-4 py-2 rounded ${
              currentPage === totalPages ? "bg-gray-300 text-gray-500 cursor-not-allowed" : "bg-gray-300 text-gray-700"
            }`}>
            &gt;
          </button>
        </div>
      </div>
    </div>
  )
}

export default TestCardPage
